services:
   frontend:
       build: ./apps/web
       command: pnpm dev
       ports:
         - "3000:3000"
       volumes: 
         - ./apps/web:/app
         - /app/node_modules
       working_dir: /app

   backend:
    build: ./apps/api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./apps/api:/app
    working_dir: /app